"""initial production schema

Revision ID: 7644277b1d6d
Revises: 
Create Date: 2026-07-31 19:45:19.004648
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7644277b1d6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('license_class', sa.String(length=80), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('ddc_expiry', sa.Date(), nullable=True),
    sa.Column('medical_expiry', sa.Date(), nullable=True),
    sa.Column('defensive_expiry', sa.Date(), nullable=True),
    sa.Column('drug_test', sa.String(length=30), nullable=False),
    sa.Column('rest_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_name'), 'drivers', ['name'], unique=True)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('division', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=False),
    sa.Column('mfa_pending_secret', sa.Text(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_recovery_hashes', sa.Text(), nullable=False),
    sa.Column('mfa_setup_at', sa.DateTime(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('contractor', sa.String(length=160), nullable=False),
    sa.Column('vehicle_type', sa.String(length=80), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('inspection_expiry', sa.Date(), nullable=True),
    sa.Column('maintenance_due', sa.Date(), nullable=True),
    sa.Column('gps_status', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_no', sa.String(length=40), nullable=False),
    sa.Column('division', sa.String(length=160), nullable=False),
    sa.Column('site', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('start_location', sa.String(length=220), nullable=False),
    sa.Column('end_location', sa.String(length=220), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_arrival_at', sa.DateTime(), nullable=False),
    sa.Column('actual_departure_at', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival_at', sa.DateTime(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('night_drive', sa.Boolean(), nullable=False),
    sa.Column('load_type', sa.String(length=80), nullable=False),
    sa.Column('passengers', sa.Text(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('checkin_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checkin_at', sa.DateTime(), nullable=True),
    sa.Column('next_checkin_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journey_driver_window', 'journeys', ['driver_id', 'departure_at', 'estimated_arrival_at'], unique=False)
    op.create_index('ix_journey_vehicle_window', 'journeys', ['vehicle_id', 'departure_at', 'estimated_arrival_at'], unique=False)
    op.create_index(op.f('ix_journeys_created_at'), 'journeys', ['created_at'], unique=False)
    op.create_index(op.f('ix_journeys_departure_at'), 'journeys', ['departure_at'], unique=False)
    op.create_index(op.f('ix_journeys_division'), 'journeys', ['division'], unique=False)
    op.create_index(op.f('ix_journeys_driver_id'), 'journeys', ['driver_id'], unique=False)
    op.create_index(op.f('ix_journeys_estimated_arrival_at'), 'journeys', ['estimated_arrival_at'], unique=False)
    op.create_index(op.f('ix_journeys_journey_no'), 'journeys', ['journey_no'], unique=True)
    op.create_index(op.f('ix_journeys_next_checkin_at'), 'journeys', ['next_checkin_at'], unique=False)
    op.create_index(op.f('ix_journeys_requester_id'), 'journeys', ['requester_id'], unique=False)
    op.create_index(op.f('ix_journeys_risk_level'), 'journeys', ['risk_level'], unique=False)
    op.create_index(op.f('ix_journeys_status'), 'journeys', ['status'], unique=False)
    op.create_index(op.f('ix_journeys_vehicle_id'), 'journeys', ['vehicle_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('required_role', sa.String(length=40), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'stage', name='uq_approval_stage')
    )
    op.create_index(op.f('ix_approvals_approver_id'), 'approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approvals_journey_id'), 'approvals', ['journey_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('checklist_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=80), nullable=False),
    sa.Column('item_text', sa.String(length=500), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'item_key', name='uq_checklist_answer')
    )
    op.create_index(op.f('ix_checklist_answers_journey_id'), 'checklist_answers', ['journey_id'], unique=False)
    op.create_table('journey_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_events_created_at'), 'journey_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_journey_events_event_type'), 'journey_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_journey_events_journey_id'), 'journey_events', ['journey_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('risk_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'question_key', name='uq_risk_answer')
    )
    op.create_index(op.f('ix_risk_answers_journey_id'), 'risk_answers', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_answers_journey_id'), table_name='risk_answers')
    op.drop_table('risk_answers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_journey_events_journey_id'), table_name='journey_events')
    op.drop_index(op.f('ix_journey_events_event_type'), table_name='journey_events')
    op.drop_index(op.f('ix_journey_events_created_at'), table_name='journey_events')
    op.drop_table('journey_events')
    op.drop_index(op.f('ix_checklist_answers_journey_id'), table_name='checklist_answers')
    op.drop_table('checklist_answers')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_journey_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approver_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_journeys_vehicle_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_status'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_risk_level'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_requester_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_next_checkin_at'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_journey_no'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_estimated_arrival_at'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_driver_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_division'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_departure_at'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_created_at'), table_name='journeys')
    op.drop_index('ix_journey_vehicle_window', table_name='journeys')
    op.drop_index('ix_journey_driver_window', table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_name'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
